_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": darwin-arm64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 1024
compile:
    value: true
dataset:
    value: enwik8
decay_lr:
    value: true
device:
    value: mps
dropout:
    value: 0.1
dtype:
    value: float16
eval_interval:
    value: 500
eval_iters:
    value: 200
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.0005
log_interval:
    value: 100
lr_decay_iters:
    value: 150000
max_iters:
    value: 150000
min_lr:
    value: 5e-05
n_embd:
    value: 768
n_head:
    value: 16
n_layer:
    value: 12
out_dir:
    value: out-enwik8-asadp
wandb_log:
    value: true
wandb_project:
    value: enwik8-asadp
wandb_run_name:
    value: gpt2-enwik8-asadp-1726805382.933011
warmup_iters:
    value: 2000
weight_decay:
    value: 0.1
